name       : simplescreenrecorder
version    : 0.3.4
release    : 3
source     :
    - https://github.com/MaartenBaert/ssr/archive/0.3.4.tar.gz : 99afd25cc4c3e2bcfcd04cdd3c957507928982735951cf5b3aba91b8c216debd
license    : GPL-3.0
summary    : A screen recorder for Linux 
description: |
    A screen recorder for Linux 
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(libavformat)
    - pkgconfig(libpulse)
    - pkgconfig(alsa)
    - pkgconfig(x11)
    - pkgconfig(xi)
    - pkgconfig(xfixes)
    - pkgconfig(gl)
    - pkgconfig(glu)
libsplit   : no
clang      : no
setup      : |
    %configure --disable-assert \
               --without-jack \
               --with-qt5 \
               --enable-glinjectlib
build      : |
    %make
install    : |
    %make_install
