name       : simplescreenrecorder
version    : 0.3.3
release    : 2
source     :
    - https://github.com/MaartenBaert/ssr/archive/0.3.3.tar.gz : cb75df563927d3fa74cb825c9040522332c49cd9745e02c8a64be0bff0aeac26
license    : GPL-3.0
summary    : A screen recorder for Linux 
description: |
    A screen recorder for Linux 
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(libavformat)
    - pkgconfig(libpulse)
    - pkgconfig(alsa)
    - pkgconfig(x11)
    - pkgconfig(xi)
    - pkgconfig(xfixes)
    - pkgconfig(gl)
    - pkgconfig(glu)
libsplit   : no
clang      : no
setup      : |
    %configure --disable-assert \
               --without-jack \
               --with-qt5 \
               --enable-glinjectlib
build      : |
    %make
install    : |
    %make_install
