name       : simplescreenrecorder
version    : 0.4.3
release    : 23
source     :
    - https://github.com/MaartenBaert/ssr/archive/0.4.3.tar.gz : 03b5f6cd613b504f8b2351c2728a6fd070aa0cc98e709bcafdcf93b672bd2b71
homepage   : http://www.maartenbaert.be/simplescreenrecorder/
license    : GPL-3.0-or-later
component  : multimedia.video
libsplit   : no
summary    : A screen recorder for Linux
description: |
    SimpleScreenRecorder is a screen recorder for Linux. Despite the name, this program is actually quite complex. It's 'simple' in the sense that it's easier to use than ffmpeg/avconv or VLC.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(glu)
    - pkgconfig(libavformat)
    - pkgconfig(libpulse)
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(libv4l2)
    - pkgconfig(xfixes)
    - pkgconfig(xi)
    - pkgconfig(xinerama)
setup      : |
    %cmake -DCMAKE_INSTALL_LIBDIR=%libdir% \
        -DWITH_JACK=FALSE \
        -DWITH_QT5=TRUE
build      : |
    %make
install    : |
    %make_install
