name       : simplescreenrecorder
version    : 0.3.9
release    : 16
source     :
    - https://github.com/MaartenBaert/ssr/archive/0.3.9.tar.gz : f3820eadaf9ecfe9aaf0940bf868cedd828c6e75b6a860195ecc091c174fcebe
homepage   : http://www.maartenbaert.be/simplescreenrecorder/
license    : GPL-3.0
component  : multimedia.video
libsplit   : no
summary    : A screen recorder for Linux
description: |
    SimpleScreenRecorder is a screen recorder for Linux. Despite the name, this program is actually quite complex. It's 'simple' in the sense that it's easier to use than ffmpeg/avconv or VLC.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gl)
    - pkgconfig(glu)
    - pkgconfig(libavformat)
    - pkgconfig(libpulse)
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(x11)
    - pkgconfig(xfixes)
    - pkgconfig(xi)
setup      : |
    %cmake -DCMAKE_INSTALL_LIBDIR=%libdir% \
        -DWITH_JACK=FALSE \
        -DWITH_QT5=TRUE
build      : |
    %make
install    : |
    %make_install
