name       : simplescreenrecorder
version    : 0.3.11
release    : 20
source     :
    - https://github.com/MaartenBaert/ssr/archive/0.3.11.tar.gz : 54f5c349c54694038586d3dfe0014da5d83044d0cf0ed9c0de525ddc54cbd150
homepage   : http://www.maartenbaert.be/simplescreenrecorder/
license    : GPL-3.0-or-later
component  : multimedia.video
libsplit   : no
summary    : A screen recorder for Linux
description: |
    SimpleScreenRecorder is a screen recorder for Linux. Despite the name, this program is actually quite complex. It's 'simple' in the sense that it's easier to use than ffmpeg/avconv or VLC.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gl)
    - pkgconfig(glu)
    - pkgconfig(libavformat)
    - pkgconfig(libpulse)
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(x11)
    - pkgconfig(xfixes)
    - pkgconfig(xi)
setup      : |
    %cmake -DCMAKE_INSTALL_LIBDIR=%libdir% \
        -DWITH_JACK=FALSE \
        -DWITH_QT5=TRUE
build      : |
    %make
install    : |
    %make_install
