name       : simplescreenrecorder
homepage   : http://www.maartenbaert.be/simplescreenrecorder/
version    : 0.3.8
release    : 12
source     :
    - https://github.com/MaartenBaert/ssr/archive/0.3.8.tar.gz : ef05f1b4c36e1d82a4e96f59c5f29aaae986ad6711ccc311d0e21c8e6c191c6d
license    : GPL-3.0
component  : multimedia.video
summary    : A screen recorder for Linux
description: |
    A screen recorder for Linux
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gl)
    - pkgconfig(glu)
    - pkgconfig(libavformat)
    - pkgconfig(libpulse)
    - pkgconfig(Qt5Core)
    - pkgconfig(x11)
    - pkgconfig(xfixes)
    - pkgconfig(xi)
libsplit   : no
clang      : no
setup      : |
    %configure --disable-assert \
        --enable-glinjectlib \
        --without-jack \
        --with-qt5
build      : |
    %make
install    : |
    %make_install
