name       : simplescreenrecorder
version    : 0.4.2
release    : 22
source     :
    - https://github.com/MaartenBaert/ssr/archive/0.4.2.tar.gz : a6da4979c7c3f402ea93e43f1c55e289cdcc69653a1a128e32e8bd59481b2511
homepage   : http://www.maartenbaert.be/simplescreenrecorder/
license    : GPL-3.0-or-later
component  : multimedia.video
libsplit   : no
summary    : A screen recorder for Linux
description: |
    SimpleScreenRecorder is a screen recorder for Linux. Despite the name, this program is actually quite complex. It's 'simple' in the sense that it's easier to use than ffmpeg/avconv or VLC.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(glu)
    - pkgconfig(libavformat)
    - pkgconfig(libpulse)
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xfixes)
    - pkgconfig(xi)
    - pkgconfig(xinerama)
setup      : |
    %cmake -DCMAKE_INSTALL_LIBDIR=%libdir% \
        -DWITH_JACK=FALSE \
        -DWITH_QT5=TRUE
build      : |
    %make
install    : |
    %make_install
