name       : simplescreenrecorder
version    : 0.4.4
release    : 25
source     :
    - https://github.com/MaartenBaert/ssr/archive/refs/tags/0.4.4.tar.gz : 69fccf8df6e7285d4df5033eed8748f4eae13b407488906dcf4810a277d557b8
homepage   : http://www.maartenbaert.be/simplescreenrecorder/
license    : GPL-3.0-or-later
component  : multimedia.video
libsplit   : no
summary    : A screen recorder for Linux
description: |
    SimpleScreenRecorder is a screen recorder for Linux. Despite the name, this program is actually quite complex. It's 'simple' in the sense that it's easier to use than ffmpeg/avconv or VLC.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(glu)
    - pkgconfig(libavformat)
    - pkgconfig(libpulse)
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(libv4l2)
    - pkgconfig(xfixes)
    - pkgconfig(xi)
    - pkgconfig(xinerama)
setup      : |
    %cmake -DCMAKE_INSTALL_LIBDIR=%libdir% \
        -DWITH_JACK=FALSE \
        -DWITH_QT5=TRUE
build      : |
    %make
install    : |
    %make_install
